language: php

matrix:
    include:
        - php: 5.3
          env: PHPUNIT_GROUPS="--exclude-group trait"
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: hhvm

install:
    - composer install --dev

script: ./vendor/bin/phpunit $PHPUNIT_GROUPS
